export const projects = [
    {
        id: 1,
        img: "./dl.jpg",
        title: "Digital Library System",
        desc: "Serves faculty, students, and researchers. Includes services application, communication features, admin and employee management, and report generation.",
        long_desc: "The library serves a large segment of beneficiaries, such as faculty members, graduate students, and undergraduate students, in addition to other research and educational institutions such as private and private universities and educational institutes. As well as scientific magazines and periodicals inside and outside the university. The System has 6 views.",
        organisation: "Associated with Helwan University",
        date: "09/2023 – 12/2023",
        programming_language: "R - N - J - E - M  - C - H" ,
        proLinK: "",
        githubLink: "",
    },
    // : The user can apply for any of the eight available services and communicate with the library through the site's chat and many other features to facilitate service request and communication. There is an admin for each service and employees who are divided into (examiner and reviewer) and an employee who specializes in payment codes and they have many features such as distributing requests among them, controlling the employee's powers, communicating between them and users, printing various reports on the need and many other features, and finally the library manager who manages the employees and service managers on the site. Adding important events for users
    {
        id: 2,
        img: "./Li.png",
        title: "Live Chat Website",
        desc: "Real-time chat website with user status and typing indicators. Ensures a seamless and responsive chat experience.",
        long_desc: "Live chat website enabling real-time communication between users. Provided features to display user status (online/offline) and indicate when users are typing. Focused on delivering a seamless and responsive chat experience, ensuring high performance and reliability.",
        organisation: "Personal project",
        date: "04/2024",
        programming_language: "R - N - J - E - M - B - P  - C - H" ,
        proLinK: "",
        githubLink: "",
    },
    {
        id: 3,
        img: "./gr.png",
        title: "System for Postgraduate Studies",
        desc: "Allows applicants to apply for programs, upload attachments, and track applications. Faculty and university employees manage and process applications.",
        long_desc: "The System has 4 views: The applicant is granted the right to apply for any program in all faculties of Helwan University once per semester to upload all attachments required for the chosen program, follow up on the status of his application, and modify his data or attachments if requested to do so. The faculty employee adds the departments and programs of his faculty, receives the sent applications, and can return the application for modification by the applicant or rejection or acceptance to the applicant, after acceptance, the application is sent to the university employee for final acceptance. Finally, we have a super admin to manage all of this.",
        organisation: "Associated with Helwan University",
        date: "07/2023 – 08/2023",
        programming_language: "R - N - J - E - M  - C - H" ,
        proLinK: "",
        githubLink: "",
    },
    {
        id: 4,
        img: "./gr.png",
        title: "Application System for the Faculty of Law",
        desc: "Manages applications for Faculty of Law programs. Streamlines the application process for prospective students.",
        long_desc: "Created a dedicated application system for managing applications to the distinctive programs offered by the Faculty of Law. Focused on providing a streamlined and efficient application process for prospective students.",
        organisation: "Associated with Helwan University",
        date: "07/2023 – 08/2023",
        programming_language: "R - N - J - E - M - C - H" ,
        proLinK: "",
        githubLink: "",
    },
    {
        id: 5,
        img: "./p.jpeg",
        title: "Personal Portfolio",
        desc: "Personal portfolio website. Includes features such as contact form, social media links, and responsive design.",
        long_desc: "Personal portfolio website. Includes features such as contact form, social media links, and responsive design. Focused on providing a seamless and user-friendly experience.",
        organisation: "Personal project",
        date: "06/2023",
        programming_language: "R - J - B - C - H",
        proLinK: "",
        githubLink: "",
    }
    
];
